### PR TITLE
rewrote the script using ood, needs testing / a code review

### PR DESCRIPTION
**Pull request by sudopluto**
got around to rewriting the script, organizing it around video and image objects 
kept the old script with the prefix 'old-', and in initial testing there seems to be no difference between 
the original and the redesign. 

i tried write as much as I could as pure functions so that we can add tests easier latter on needed'

this needs some more real world testing / a code review

### CODE REVIEW

**Comment by NathanLovato** [comment]
Works well, thanks. Merging and then gonna tweak a few things if that's okay for you (only variable names).
What does `# warning: side effects` mean? That the method is procedural?

**Comment by NathanLovato** [comment]
By the way next time no need to keep a copy of the old script: we're using git so we always have a history of the changes.

**Comment by sudopluto** [comment]
the side effects warning is just a note for possible testing for the future, since those methods would need extra work in their tests

**Comment by NathanLovato** [comment]
Got it, thanks! Don't worry too much about this for now. Pure functions could get unit tests eventually, but for now I feel the tool isn't big enough for us to bother with that. And as long as the code stays clean we can add them anytime.
Thanks much for your help once again! :)

**Comment by NathanLovato** [comment]
By the way for some reason you don't appear in the contributors. Is it because your work isn't on the master branch yet?

**Comment by sudopluto** [comment]
sounds good. as for the contributor part, I think a commit is needed on the master brach to show up on github

**Pull request merged**
