### PR TITLE
Added operator to swap 2 strips and some utils

### PR DESCRIPTION
**Pull request by Blezyn**
3 files were added.

- operators/utils/move_final_start.py: Moves a strip based on its frame_final_start without changing its duration.
- operators/utils/swap_strips.py: Swaps 2 strips between them. More specific, places the first strip in the channel and starting frame (frame_final_start) of the second strip, and places the second strip in the channel and starting frame (frame_final_end) of the first strip. If the biggest in duration strip doesn't fit in the space of the smallest strip, it does nothing.
- operators/swap_strips_op.py: Uses the swap_strips module to swap 2 selected strips.

*This is my first time using Github, and contribution to an open source project. If I messed or did something wrong, I apologize in advance. If thats the case, any tip would be appreciated. Thanks.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thanks a lot for your help! I'll merge as-is, and reorganize a few things on top of it. Some feedback:

1. Avoid inline comments in your code in general (comments starting with #, not docstrings). Code should self-documenting, and if it's not, you want to use clearer function and variable names. 
2. Your procedural swap_strips function is the operator's functionality, not a utility. It shouldn't be in another file. If we want to swap strips from another operator, we will call the operator directly anyway, as it should encapsulate all the functionality: `bpy.ops.power_sequencer.swap_strips(args)`
3. move_final_start, to start with, as it's only used in one place, you should have it as one of the operator's methods. Otherwise you create 3 files to navigate through to understand an operator, while it could be one chunk of self-contained behavior

A general tip: to compare, sort, or get any object type based on some property, you can often use built-in functions with operator.attrgetter. This type of code:

```py
    if strip_1.frame_final_duration > strip_2.frame_final_duration:
        big_strip = strip_1
        small_strip = strip_2
    else:
        big_strip = strip_2
        small_strip = strip_1
```

Can work without conditional blocks this way:

```py
from operator import attrgetter
...
strip_longer = max(strips, key=attrgetter('frame_final_duration'))
strip_shorter = min(strips, key=attrgetter('frame_final_duration'))
```

or

```py
from operator import attrgetter
...
strips = sorted([strip_1, strip_2], key=attrgetter('frame_final_duration'))
strip_longer, strip_shorter = strips[0], strips[1]
```

I'll go into the code now and link to the changes/commit in a few moments

**Comment by NathanLovato** [comment]
Big thanks for the work you've done documenting your commits and functions by the way! Much appreciated

**Comment by NathanLovato** [comment]
A quick example of good inline comments. It's ok to sum up a code block that could take some time to decipher otherwise:
image

**Comment by NathanLovato** [comment]
There are a few opportunities to use built-in functions in your code. Another example of attrgetter with max:
```py
end_frame = 0
for s in sequences:
     if end_frame < s.frame_final_end:
            end_frame = s.frame_final_end
```
⬇
```py
end_frame = max(sequences, key=attrgetter('frame_final_end'))
```

**Comment by NathanLovato** [comment]
There you go! https://github.com/GDquest/Blender-power-sequencer/commit/544099dde7549400997a622d08aece6b01d853d9

The final file is shorter than the previous 3, and should be self-documenting.

**Comment by Blezyn** [comment]
That was very informative and helpful. Thank you very much for your time!

**Pull request merged**
