### PR TITLE
Auto select strips modifier added to trim_left_or_right_handles

### LINKED ISSUE #320: trim_left_or_right_handles.py: Add auto select support
Add support to auto select strips... under the time cursor? Except for locked strips.
As this is a keyboard operation I think it's better to use the time cursor and not the mouse cursor to auto select.

### PR DESCRIPTION
**Pull request by guilhermehto**
Closes #320

### CODE REVIEW

**Comment by NathanLovato** [comment]
This is not how auto select works in the plugin. Now select changed in 2.80 we can change the design in PS but this is inconsistent with other features.

E.g. for concatenate: you couldn't use A C to auto select then concatenate: A is the key for "select all". Same issue with all features that support auto selection and are bound to a single letter.

The idea is if you don't have anything selected, relevant tools in PS will auto select what's under the mouse or time cursor.

**Comment by NathanLovato** [comment]
@razcore-art @henriiquecampos do you have some thoughts on that?

**Comment by guilhermehto** [comment]
> The idea is if you don't have anything selected, relevant tools in PS will auto select what's under the mouse or time cursor.

But isn't the operator doing that? That was my goal when adding the feature: select what's under the time cursor. It was working like so while testing 🤔 

As for the shortcut, I used A because it came to mind, as in Auto-select. We're out of "normal" modifiers like `shift` `ctrl` and `alt`. Though I agree with you that A is the key for selecting, in 2.79 the shortcut for playing was `alt + a`, which has nothing to do with selecting. I don't see it as a big problem, but if we can find a better solution, that would be better :)

**Comment by NathanLovato** [comment]
> But isn't the operator doing that?

As I told you it's not consistent with how PS works. Every other operator that auto selects doesn't need any extra key or modifier: if you have no strip selected, they auto select.

Deselect everything, press C, and PS will concatenate based on the strip under the mouse cursor. Press x and PS will delete the strip under the mouse cursor. etc.

**Pull request merged**
