### PR TITLE
blender 2.80 port

### PR DESCRIPTION
**Pull request by razcore-art**
At the moment it registers the plugin (operators), I need to go through registering the shortcuts & updating the auto-update script.

### CODE REVIEW

**Comment by razcore-art** [comment]
@NathanLovato when you got a chance could you check to see if there's any major issues after porting? You can follow the command line instructions button near `Merge pull request` to make a temp branch and play with the port.

I got an error on checking for the addon version update, but I think this has got to do with how the python interpreter is built for blender, I'm not sure if there's anything we can do about it, maybe on your machine it works so then we have to figure out what's different. It's an ssl error, meaning the python interpreter needs to be built with ssl support and it seems that the blender version I got doesn't have this. We might need to get in touch with some blender devs for that.

**Comment by NathanLovato** [comment]
MouseCut (the modal operator to cut and trim strips) isn't working here. After some quick tests, besides that, it seems fine.
Regarding the error you got, is this related to the add-on updater? If so, we probably need to update this one from upstream as well: https://github.com/CGCookie/blender-addon-updater/releases

**Comment by razcore-art** [comment]
Ah, I see that there's something new with `bgl` (on MouseCut):

```
Traceback (most recent call last):
  File "/home/razvan/.config/blender/2.80/scripts/addons/bps/operators/mouse_cut.py", line 279, in draw_cut_trim
    bgl.glPushMatrix()
AttributeError: module 'bgl' has no attribute 'glPushMatrix'
```
I also had to change some shortcuts to use `LEFTMOUSE`/`RIGHTMOUSE` because there's no `ACTIONMOUSE` value any more.

About the SSL error it might be related to this: https://github.com/CGCookie/blender-addon-updater/issues/39. I just skimmed through, the error seems to be in some other place in `_ssl.c`, but our best bet is probably to just update that issue with our version of the error, I'll have to go through it more thoroughly, it seems those guys think it's related only to blender 2.7x.

I didn't realize this is a separate addon project, it might be worth making it an actual git subrepository/subproject to easily update it

**Comment by razcore-art** [comment]
I'd say this is ready to merge, just fixed mouse cut operator. One thing you'll notice is that on the bottom status bar panel names like `POWER_SEQUENCER_OTMouseCut` will appear, probably generated by blender from the class names, I'm not sure how to modify those.

There's also a bug with addon updater that we discussed about - the SSL python error. I also formatted auto updater using a python formatter cause it was using tabs instead of spaces, but at the time I didn't know it's a separate project. It shouldn't matter though.

**Comment by NathanLovato** [comment]
I think we can even call it BPS 1.3 with just this PR :D

**Comment by razcore-art** [comment]
I think I actually modified the version to 1.3 in `__init__.py` too :))

**Comment by brousselle** [comment]
love you all guys :D so happy to see it back in 2.80 !!

**Pull request merged**
