### PR TITLE
[WIP]  GUI panel for BPSProxy

### PR DESCRIPTION
**Pull request by davcri**
This is a WIP for #302 (UI: Interface for BPSProxy). I'm making a PR to have early feedback/code review.

I managed to run bpsproxy in the background and update show a progress report, following [these advices](https://blender.stackexchange.com/questions/1050/blender-ui-multithreading-progressbar).

Unfortunately I have 2 issues:

1. the mouse progress interface is pretty ugly:
cursor
2. I still have to implement data communication between `bpsproxy` and the Blender

---

So my questions are:

1. Is it worth continuing down this path? It seems like Blender doesn't put a lot of effort in this part of the API, and IDK what are the plans for v2.80
2. What do you think it's the best way to exchange data from bpsproxy and the plugin?

### CODE REVIEW

**Comment by razcore-art** [comment]
Right, first of all thanks for your contribution @davcri, much appreciated.

Now for the code, like I said in the discord chat, I don't think it's a good idea to try and tie `bpsproxy` (or `bpsrender`) this way with power sequencer. `bpsproxy` should be used instead as a module and the functions should be called directly probably through either `threading` or `multiprocessing` although I'd go with `multithreading`. There's almost always no need for work with `threading` which is a bit more trouble in Python.

We'd just make our lives harder if we tried to run `bspproxy` as a command line utility via `subprocess` since there's no easy way to get progress. I don't really know how to get into specifics at this point, but if you check `bpsrender`, specifically the call to [the video command](https://gitlab.com/razcore/BPSRender/blob/master/bpsrender/calls.py#L212) you see an example of how I get data from the individual calls from `call_chunk` via `multiprocessing` using `Queue`. Now I'm not exactly an expert myself and there might be an easier way to do this, but this seems to work quite fine and I think can be translated quite well for your use case for `bpsproxy`.

Hope this will give you a direction to follow and if you have specific questions let me know.

**Comment by davcri** [comment]
Hi @razcore-art! Sorry for the delay in the answer. 
Thank you for the code example. I'll take a look at `multithreading` and `Queue` and try to refactor this PR.

I was wondering: do you think that the GUI is one of the feature that we want to keep for the 2.8 release?  
I'm asking this especially because of what @NathanLovato [wrote yesterday](https://github.com/GDquest/Blender-power-sequencer/issues/316) about the future of PS.

I think that a GUI is useful for newcomers, but it's not the most efficient workflow.   
It's better to use shortcuts and command line (for bpsrender and bpsproxy).

**Comment by NathanLovato** [comment]
Accessibility and making features discoverable is important for users so let's keep the UI, and strive to create efficient UI.

**Comment by cgvirus** [comment]
I have a proposal if subprocess is not in favor; 
we can create .sh file for Linux/OSX and .bat file for win. This can be created in the auto created directory 'BL_Proxy' and user can 

sh movie25.sh or double click the movie25.bat if multithreading is needed.

I was planning to create a button for this just a moment ago, seems it's already planned. Let me know if helping hand is needed. Thanks.

**Comment by NathanLovato** [comment]
Hi Davide,

Could you give me an update on this PR? Do you still want to finish? If you don't have the time to work on it, may we take over and finish implementing it?

**Comment by davcri** [comment]
HI @NathanLovato,

sure you can take it. Feel free to reach me out if you need anything else.
  
I'm sorry for not completing this PR, I hope this didn't slow you down. However, I'll follow the development to learn as much as I can (hoping to be more helpful in the future).

**Comment by NathanLovato** [comment]
No problem! Thanks, I'll manually merge later.

**Comment by NathanLovato** [comment]
I don't have time to work on this feature or bpsproxy. It's too much work for what it's worth, I feel. Hopefully the focus on the sequencer in 2021 will bring enough performance and UX improvements we can drop it completely.

Closing the PR for now.

**Pull request closed without merging**
