### PR TITLE
Readme imgs

### PR DESCRIPTION
**Pull request by cspeterson**
# Key images

The doakey svg key images were rawgit urls, and rawgit is going away

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
> If you're currently using RawGit, please stop using it as soon as you can.
> - [rawgit.com](https://rawgit.com)

# Demo images and logo

Were not part of the repo and the logo version was out of date

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thanks a lot for the PR! The images need to be changed straight in the source code, from which we generate the docs, not in the README file. You have to look for 'demo': 'url' in the operators/ folder. It seems you can do that with a sed or grep command. Can you do it or would you like me to do it for you?

Also @doakey3 as these are your images, is it okay if we add them to the repo?

**Comment by doakey3** [comment]
The images are free to use for whatever.

**Comment by NathanLovato** [comment]
Thanks much 🙂
I wasn't sure about the licence.

**Comment by cspeterson** [comment]
# Demo images

I've worked the demo images into the repo as you described. I couldn't get the doc generator utility working though so I'll leave actually getting this stuff into the final README up to someone else. 🙂

# Key images

It occurred to me, should this project keep using those key images? I see the <kbd> element used in Blender-power-sequencer-docs, and it's a lot less to worry about.
[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd]

**Comment by NathanLovato** [comment]
Thanks! Thinking about it, we should definitely use the kbd tags, that's that many image queries removed from the page.

Also, now the docs are on [our website](https://www.gdquest.com/blender/power-sequencer/docs/), I'd rather not have to maintain that .RST file: it's a lot more flexible and easier to work with hugo and css. We can also integrate video tutorials etc., have everything in one place. The template needs some improvement but at least the content is in place.

**Comment by cspeterson** [comment]
There was until very recently a separate repo for BPS docs, no? I don't see it anymore.

Yeah anyway, as a user of the plugin, so long as it's easy to reach the full docs from the README I think I'd be happy enough 🙂

**Pull request closed without merging**
