### PR TITLE
Extract shortcut/docs from operator classes

### PR DESCRIPTION
**Pull request by razcore-art**
A first idea of how to extract information from operators to generate
docs and shortcuts in the `json` format. Moved all info into a variable
called `doc` in the operators, the `description` entry in the `doc`
dictionary can for example be `__doc__` (the class documentation). This
is the simplest solution I found. I've done this only for `CrossfadeEdit`
as an example (doesn't have a shortcut cause it isn't registered with a
shortcut at the time of this writing).

The python script to generate the `json` file is very simple and it's in
`scripts/ShortcutsDocs`. It has to be ran through Blender (because of
`bpy` and other Blender modules), hence the
`scripts/ShortcutsDocs/shortcuts_docs.sh` script.

Extra shortcuts (that aren't linked to power sequencer operators) are
stored in `doc` inside of `operators/__init__.py`. So far works pretty
well, but I can't test the readme generation, cause I don't have hugo

### CODE REVIEW

**Comment by NathanLovato** [comment]
Looking good to me, having an extensible data struct in each operator. Why not use the class's docstring for the description though, as having docstrings is standard in py?

Anyway removing the separation between the two shortcut files will be a good step in the right direction already. You can work on any of your tasks in any order. It was low priority to me back when I created it because it's time consuming, and I needed other tools in priority. But the situation is different now

**Comment by razcore-art** [comment]
@NathanLovato 
cool, so the reason I didn't use the docstring to store all data (name, demo link, description, shortcuts) is cause it would have been more complicated to destructure and extract it to then create the json file. The reason why `doc['description']` isn't the docstring yet so we can do `doc['description'] = __doc__` :) - which is something I want to do - is cause I copied the info form `shortcuts_docs.json` which differs from the original docstring so I didn't know if you want to rewrite the docstring with the description from the `json` or not. That's what I'd do, like in the `CrossfadeEdit` example. Did that one like this because it originally didn't have a docstring.

**Comment by NathanLovato** [comment]
Makes sense. I'd say go ahead and merge the descriptions and docstrings. They'll need a full refresh/pass for the next release anyway, there's been lots of changes

**Comment by razcore-art** [comment]
I just pushed the changes with generated docs/descriptions/names etc, but I can't merge yet because we have to make sure all the `bl_idnames` are correct, plus we need to start thinking about the class names by this point since `bl_label` is also generated from it

**Comment by razcore-art** [comment]
We can think of `bl_label` later, but `bl_idname` is pretty important :)

**Comment by NathanLovato** [comment]
@razcore-art Feel free to open an issue with your proposal to standardize the code, we can include discussion about class names there

**Comment by razcore-art** [comment]
so this should be ready to merge, but it needs some second pair of eyes just to be sure.

now that this is done, I can open up the proposal for the naming convention etc. I have to think about it a bit, not easy coming up with good names :)

**Comment by NathanLovato** [comment]
Looking good to me. I can't test it now but you can go ahead, merge, and we can add improvements and fixes later if need be

**Pull request merged**
