### PR TITLE
Panel started

### PR DESCRIPTION
**Pull request by doakey3**
I've started creating a panel for Power-Sequencer in response to [#90](https://github.com/GDquest/Blender-power-sequencer/issues/90). 

Proposals:
* Panel will appear only in the properties menu for the sequencer (not the Image Preview or anywhere else).
* The panel will go in a tab called "Tools" instead of the default tabs "Strips" or "Modifiers"
* The panel will be closed by default.

Other changes:
* Added "linker.py" to .gitignore
* Changed the "concatenate_sequences.py" filename to "concatenate_strips.py" for consistency.
* Added a few lines to the `__init__.py` to enable the panel and it's only button.

If you're alright with these proposals, I'll make the panel more complete.

### CODE REVIEW

**Comment by doakey3** [comment]
I took a crack at [#18](https://github.com/GDquest/Blender-power-sequencer/issues/18).

Proposals:
* Added "keymap.json" file to the `/utils` folder
    - Each keymap item is separated by the name of the keymap, space_type, and region_type.
    - The keymap item is the operator id, followed by a list: type, value, modifiers (can be multiple)
    - The keymap item may also be the operator id, followed by an empty list. (To show what operations could have hotkeys) Check `/utils/keymap.json` to see what I mean.
* Added "register_keymap.py" to `/utils`
    - This function is called by `/__init__.py`
    - Searches through `/utils/keymap.json` and adds the keyboard shortcuts to Blender's "Blender Addon" keyconfig.
  - Prints out any conflicts it finds. This isn't perfect however. To detect a match, the conflicting keyboard shortcut must be assigned to the same space_type and region. However some shortcuts may conflict even when not assigned to the same space_type and region. For example, when [VSE_Transform_Tools](https://github.com/doakey3/VSE_Transform_Tools) sets up, it sets it's keyboard shortcuts for the entire Sequence Editor, then narrows the operator down to the Image Preview window in the poll function. (This is dirty. I will change this for VSE_Transform_Tools, but just know this problem exists)
 * Added "unregister_keymap.py" to `/utils`
    - This function is called by `/__init__.py`
    - Cycles through keymap items in `/utils/keymap.json` and removes those hotkeys from blender
* Added "export_keymap.py" to `/operators`
    - Cycles through all keymap items in Blender's "Blender Addon" keyconfig and collects any operator id's that start with "power_sequencer"
    - Checks current `/utils/keymap.py` file and includes any available operators without any hotkey (making it easy for users to know what operators *could* have a hotkey)
    - Writes a json file to user's specified location
* Added "import_keymap.py" to `/operators`
    - Copies user specified json file into `/utils` and renames it to "keymap.json"
    - Gives warning to user that Blender must be restarted for new keymap to take effect
* `/__init__.py` was minimally updated to enable new features
* `/addon_preferences.py` was updated to create 2 new buttons (Import and Export)

**Comment by doakey3** [comment]
It might be good to add another button to the preferences window "Default Keymap" that generates the keymap from python code.

I think the addon_updater will not overwrite the keymap.json file. This is both good and bad. Good because new updates won't overwrite user defined keymaps, bad because new default keymaps won't get updated in newer versions.

I could make the import_keymap operator edit the updater_status.json file to include some persistent marker indicating the user has created their own keymap. When register_keymap is called, it could check if this marker exists and overwrite the keymap.json with a default if the marker isn't there.

**Comment by NathanLovato** [comment]
Thank you very much for your work! It's super appreciated. Looked into the code and it's neat :)

> What do you think of turning updater.verbose to False in /addon_updater_ops.py? Currently, it just makes a lot of noise in the console

Sure no problem. Doing it now.

For the register_keymap it'll unregister and try to force register them every time you launch Blender right? Gotta test it out and see how it works but we can try this for now. Apparently that's how most Blender add-ons do it right?

**Comment by doakey3** [comment]
If you trust me, could I be made into a collaborator? This way I could add helpful changes directly to the project without making a pull request. I'll still ask before adding anything questionable.

**Comment by NathanLovato** [comment]
Sure no pb, sent an invitation

**Comment by doakey3** [comment]
I didn't seem to get an invite. Maybe you can email me the link? github.dmodo@spamgourmet.com

**Comment by doakey3** [comment]
I made some updates... If you're still ok with me helping out, can I be made into a collaborator for the [docs](https://github.com/GDquest/Blender-power-sequencer-docs/) page as well?

**Comment by NathanLovato** [comment]
Sure, doing this now :)

**Pull request closed without merging**
